# Generated by Django 5.2.17 on 2026-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'name']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='admitted_no',
            new_name='admitted_on',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year_of_admission',
            new_name='year_of_study',
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
