# Generated by Django 5.2.17 on 2026-09-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
